### ISSUE TITLE
Circlip is missing

### ISSUE THREAD

**Issue by dpriskorn** [ringgaard/sling#7]
Circlip does not show up in the top of the search results.
![Skärmbild_2021-03-17_19-12-36](https://user-images.githubusercontent.com/68460690/111517078-f6a5dd80-8754-11eb-846f-8be0f18602fe.png)
![Skärmbild_2021-03-17_19-12-55](https://user-images.githubusercontent.com/68460690/111517089-fa396480-8754-11eb-91f8-950c0fab346b.png)

**Comment by ringgaard** [comment]
The screen dump looks like it is showing the results for "cir" instead of "circlip". This could happen if the results for "cir" arrives later than the results for "circlip". I currently don't track the order of the incremental search queries, but it seems like this is needed for this to work robustly over the Internet. I think it is relatively simple to cancel queries in progress before sending a new query.  Let me take a look at this and report back.

**Comment by ringgaard** [comment]
I have [changed](https://github.com/ringgaard/sling/commit/de7c564d34ac1c87681bbb710051aa9771690fa2) the browser so pending API queries are cancelled before sending new ones. Please let me know if this fixes the problem for you.

**Comment by dpriskorn** [comment]
It's fixed now 😃

**Comment by ringgaard** [comment]
I think I have seen this bug twice after I made the fix, so I am reopening this issue again. Apparently the fix with the Abort controller does not always work.

**Comment by ringgaard** [comment]
I have changed the approach to avoiding stale query results. I now check that the query for the results matches the current value of the search input box before updating the search list.
